gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "You'll face the ultimate\n"
	.string "challenge!\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "The GAUNTLET awaits!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Who do you look like?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN}, the brave challenger\n"
	.string "ready to take on the GAUNTLET!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your GAUNTLET challenge begins now!\p"
	.string "Face the 151 POKéMON one by one.\p"
	.string "Show me what you're made of!\p"
	.string "$"
